#!/bin/sh
echo "🔍 Running Biome check..."
npx biome check --write --staged --no-errors-on-unmatched

echo "🎨 Running Biome format..."
npx biome format --write --staged --no-errors-on-unmatched

echo "📦 Adding fixed files to stage..."
git add --update

echo "✅ Pre-commit checks passed!"